### PR TITLE
Fix multiple bugs related to nullability annotations

### LINKED ISSUE #246: `nullable::` annotation does not work for imported types
The `nullable::` annotation does not work on imported types. (It results in an `IllegalStateException` being thrown when trying to load the schema.) This is a regression that was introduced in the 1.5.0 release.

### PR DESCRIPTION
**Pull request by popematt**
**Issue #, if available:**

Fixes #246 

**Description of changes:**

Basically, when constructing a `TypeNullable`, in the `init` block, it tries to check the Ion type of the type that it is decorating. If it determines that the Ion type is `IonType.DATAGRAM`, it throws an exception because there is no such thing as a null datagram. There is no nice way to fix this, so this errs on the side of being overly permissive—if we run into an unresolved type reference, the `TypeNullable` initializer swallows the exception and just moves on.

While I was working on this, I also discovered that `ion-schema-kotlin` is incorrectly allowing `nullable::` and `$null_or::` annotations on variably occurring type definitions (i.e. types with `occurs` in them), so I fixed that as well as refactoring `Occurs` while I was in there.

See 🗺️ comments for details about specific code changes.

**Related PRs in ion-schema, ion-schema-tests, ion-schema-schemas:**

https://github.com/amazon-ion/ion-schema-tests/pull/49

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

File: ion-schema/src/main/kotlin/com/amazon/ionschema/internal/DeferredReference.kt [hunk 1]
```diff
@@ -73,12 +73,14 @@ internal interface DeferredReference : TypeInternal {
...
         private fun illegalMethodCallBeforeResolving(): Nothing {
-            throw IllegalStateException("This should be unreachable because this method should not be called before the call to DeferredReferenceManager.resolve() is complete.")
+            throw UnresolvedTypeReferenceException("This should be unreachable because this method should not be called before the call to DeferredReferenceManager.resolve() is complete.")
         }
     }
     override fun getBaseType(): TypeBuiltin = if (isResolved()) resolve().getBaseType() else illegalMethodCallBeforeResolving()
     override fun isValidForBaseType(value: IonValue): Boolean = if (isResolved()) resolve().isValidForBaseType(value) else illegalMethodCallBeforeResolving()
     override fun validate(value: IonValue, issues: Violations) = if (isResolved()) resolve().validate(value, issues) else illegalMethodCallBeforeResolving()
+
+    class UnresolvedTypeReferenceException(message: String) : IllegalStateException(message)
```
Comment (popematt) [inline ion-schema/src/main/kotlin/com/amazon/ionschema/internal/DeferredReference.kt:83]: 🗺️ New exception type is so that we can safely catch and swallow it elsewhere without accidentally catching and swallowing exceptions for unrelated problems.

File: ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaContentCache.kt [hunk 2]
```diff
@@ -75,7 +76,7 @@ internal class SchemaContentCache constructor(
      * into this instance of [SchemaContentCache].
      */
     fun doesSchemaDeclareType(schemaId: String, typeId: IonSymbol): Boolean {
-        return runCatching { typeId in getSchemaContent(schemaId).declaredTypes }.getOrElse { false }
+        return runCatching { typeId.withoutTypeAnnotations() in getSchemaContent(schemaId).declaredTypes }.getOrElse { false }
```
Comment (popematt) [inline ion-schema/src/main/kotlin/com/amazon/ionschema/internal/SchemaContentCache.kt:79]: 🗺️ Comparing the `typeId` symbol with the annotations intact was causing e.g. `nullable::foo` to not be found even though `foo` type existed.

File: ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeReference.kt [hunk 3]
```diff
@@ -80,22 +84,23 @@ internal class TypeReference private constructor() {
                 is IonSymbol -> handleSymbol(ion, schema, referenceManager)
                 else -> throw InvalidSchemaException("Unable to resolve type reference '$ion'")
             }
+
+            val maybeNullableType = handleNullable(ion, schema, theType)
```
Comment (popematt) [inline ion-schema/src/main/kotlin/com/amazon/ionschema/internal/TypeReference.kt:88]: 🗺️ There's a lot of branching in this class to handle different sorts of type references. I refactored the class so that `handleNullable()` only needs to be called in one place (so that it doesn't get missed for any branches).

Basically, this means that all other calls to `handleNullable()` are removed, and all of the private functions now return `TypeInternal` instead of `() -> TypeInternal`.

File: ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Fields.kt [hunk 4]
```diff
@@ -65,7 +64,7 @@ internal class Fields(
         // Forces the field definitions to be validated
         fieldConstraints = ionStruct.associateBy(
             { it.fieldName },
-            { Occurs(it, schema, referenceManager, OPTIONAL, isField = true) }
+            { Occurs(it, schema, referenceManager, isField = true) }
```
Comment (popematt) [inline ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Fields.kt:67]: 🗺️ Just removing the now-unnecessary constructor arg for `Occurs`.

File: ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Occurs.kt [hunk 5]
```diff
@@ -92,36 +83,12 @@ internal class Occurs(
...
-                } else {
-                    defaultRange
-                }
-            } else {
-                defaultRange
-            }
+        val occurs: IonValue? = (ion as? IonStruct)?.takeIf { !ion.isNullValue }?.get("occurs")
 
-        val tmpIon = if (ion is IonStruct && occurs != null) {
-            ion.cloneAndRemove("occurs")
```
Comment (popematt) [inline ion-schema/src/main/kotlin/com/amazon/ionschema/internal/constraint/Occurs.kt:109]: 🗺️ Removing this line is the only change in this file that is part of the actual fix for prohibiting `nullable` and `$null_or` on variably occurring type definitions. All of the rest of the changes in this file are just cleaning up some overly complicated code.

File: ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonValueExtensions.kt [hunk 6]
```diff
@@ -24,9 +24,9 @@ import com.amazon.ion.IonValue
  * If this value has no annotations, returns `this`;
  * otherwise, returns a clone of `this` with the annotations removed.
  */
-internal fun IonValue.withoutTypeAnnotations() =
+internal fun <T : IonValue> T.withoutTypeAnnotations(): T =
```
Comment (popematt) [inline ion-schema/src/main/kotlin/com/amazon/ionschema/internal/util/IonValueExtensions.kt:27]: 🗺️ Receiver is made generic so that when you call this function on e.g. an IonSymbol, the result is still an IonSymbol (as opposed to an IonValue that needs to be cast back to IonSymbol).

**Review by tgregg — APPROVED** [review]
