### PR TITLE
Adds CLI tool for fixing transitive imports

### LINKED ISSUE #178: Stop imports of schemas from including transitive dependencies
`ion-schema-kotlin` needs to stop allowing transitive imports and pass [these tests](https://github.com/amzn/ion-schema-tests/pull/14/files
) in order to be compliant with the Ion Schema Specification.

This is a backwards incompatible change for certain schemas that have been relying on the current, incorrect behavior that allows transitive imports, so we should also provide a utility to automatically fix affected schemas.

### PR DESCRIPTION
**Pull request by popematt**
**Issue #, if available:**

Fixes #178 

**Description of changes:**

Adds a tool to the `ion-schema-kotlin` CLI for fixing transitive imports.

To use it, you just have to check out `ion-schema-kotlin` and run `./ion-schema-cli repair fix-transitive-imports ...` and include the directory where your schemas are stored.

This uses string manipulation (rather than DOM manipulation) to actually apply the changes so that comments and whitespace in the original file don't get clobbered.

This PR looks really big, but 28 of the files are test fixtures. There's a set of schema files that need to be fixed (test input), and a corrected version using each of the three import reconciliation strategies (expected outputs).

**Related PRs in ion-schema, ion-schema-tests, ion-schema-schemas:**

None

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

File: cli/src/test/kotlin/com/amazon/ionschema/cli/commands/repair/FixTransitiveImportsCommandTest.kt [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+                    //     cli/src/test/resources/FixTransitiveImportsCommand/input/ \
+                    //     -d cli/src/test/resources/FixTransitiveImportsCommand/output-<STRATEGY>/
+                    testNodes.add(
+                        dynamicTest("Check $relativeFile are text equivalent", actualFile.toURI()) {
+                            Assertions.assertEquals(
+                                expectedFile.readText(),
+                                actualFile.readText(),
+                            )
+                        }
+                    )
```
Comment (tgregg) [inline cli/src/test/kotlin/com/amazon/ionschema/cli/commands/repair/FixTransitiveImportsCommandTest.kt:101]: How are failures here presented to the user? I think it would be great if they failed separately from the tests that are expected not to be brittle. Can we group them together into something named obviously, like "PossiblyBrittleTests"?

**Review by tgregg — APPROVED** [review]
Nice tool

File: cli/src/test/kotlin/com/amazon/ionschema/cli/commands/repair/FixTransitiveImportsCommandTest.kt (hunk 1 above)
Comment (popematt) [reply cli/src/test/kotlin/com/amazon/ionschema/cli/commands/repair/FixTransitiveImportsCommandTest.kt:101]: Failures here are only presented to someone developing the tool. Not to a user of the tool. The test cases are named, and the potentially brittle ones are called `"Check $relativeFile are text equivalent"`. There is no risk of them failing unless you are messing with the source code of the tool and changing the text output.

Maybe brittle isn't the right word for this.

Comment (tgregg) [reply cli/src/test/kotlin/com/amazon/ionschema/cli/commands/repair/FixTransitiveImportsCommandTest.kt:101]: Yeah I understand that. Still, as a developer, I find it nice to have tests that may fail in the future due to external factors marked explicitly. Could they start failing if IonJava's text writer changed its whitespacing strategy, for example?

Comment (popematt) [reply cli/src/test/kotlin/com/amazon/ionschema/cli/commands/repair/FixTransitiveImportsCommandTest.kt]: Added a "⚠ Fragile ⚠" prefix to the name of the test cases.
